### ISSUE TITLE
Add jupyter_bokeh to PyPI

### ISSUE THREAD

**Issue by philippjfr** [bokeh/jupyter_bokeh#82]
Would be great if we could upload `jupyter_bokeh` to PyPI now that it has been announced in the bokeh release blog.

**Comment by mattpap** [comment]
I forgot about this. I had an issue with PyPI token when doing last release.

**Comment by bryevdv** [comment]
Should be in the 1pass. LMK if I can help with anything.

**Comment by bryevdv** [comment]
This is done. The issue was that the current token is narrowly scoped to just the "bokeh" project. So it could not be used to upload anything else. I made a temp all-access token and used that to do the first upload. Now we should make a new token scoped to just this project. 

FYI for uploading to pypi, need to use:

```
twine upload -u __token__ -p <token> <file>
```
